#!/bin/sh /etc/rc.common

T=99
STOP=01

start() {
	chmod +x /bin/easynet/mtls_server
	/bin/easynet/mtls_server --ca-path /etc/easynet/certs/server-cert.pem --ca-key /etc/easynet/certs/server-key.pem &
}

stop() {
	killall mtls_server
}