name: api server

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd api_server
        cargo build --release --verbose
        ls -lh ./target/release/
    - name: Run tests
      run: |
        cd api_server
        cargo test --release --verbose
    - name: Package and export
      run: |
        cd api_server
        mkdir -p target2/
        cp target/release/api_server target2/ 2>/dev/null || :
        echo "PACKAGE_PATH=$(pwd)/target2" >> $GITHUB_ENV
    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: api-server-release
        path: ${{ env.PACKAGE_PATH }}
