name: api server build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always
  
jobs:
  # binary build
  build:
    name: Build - arm64v8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.82"
          override: true
          default: true
          components: rustfmt
          profile: minimal
          target: aarch64-unknown-linux-musl

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=./api_server/Cargo.toml --release --all-features --target=aarch64-unknown-linux-musl
          use-cross: true

      - name: Exec chmod
        run: |
          cd api_server
          chmod -v a+x target/aarch64-unknown-linux-musl/release/*

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-arm64v8
          path: api_server/target/aarch64-unknown-linux-musl/release/api_server
          if-no-files-found: error