name: api server build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always
  
jobs:
  # binary build
  build-arm64v8:
    name: Build - aarch64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.82"
          override: true
          default: true
          components: rustfmt
          profile: minimal
          target: aarch64-unknown-linux-gnu

      - name: Build
        - uses: ClementTsang/cargo-action@v0.0.3
        with:
          command: build
          args: --release --all-features --target=aarch64-unknown-linux-gnu
          directory: api_server
          use-cross: true

      - name: Exec chmod
        run: |
          cd api_server
          chmod -v a+x target/aarch64-unknown-linux-gnu/release/*

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-aarch64
          path: api_server/target/aarch64-unknown-linux-gnu/release/api_server
          if-no-files-found: error
