name: mtls server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install VCPKG and dependencies
      id: vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install uthash kcp wolfssl

        # Export and extract toolchain path
        EXPORT_OUTPUT=$(./vcpkg export uthash kcp wolfssl --raw --output=temp)
        echo "======EXPORT_OUTPUT=$EXPORT_OUTPUT======"
        TOOLCHAIN_PATH=$(echo "$EXPORT_OUTPUT" | grep -oP 'CMAKE_TOOLCHAIN_FILE=\K[^ ]*')
        echo "VCPKG_CMAKE_TOOLCHAIN=$TOOLCHAIN_PATH" >> $GITHUB_ENV
        
        # Debug output
        echo "Extracted toolchain path: $TOOLCHAIN_PATH"

    - name: Configure with CMake
      run: |
        echo "current pwd: $(pwd)"
        ls -lh
        cd mtls_server
        cmake -S ./ -B ./build -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_CMAKE_TOOLCHAIN }}
        
    - name: Build
      run: |
        cd mtls_server
        cmake --build ./build --config Release
        ls -lh ./build

    - name: Package and export
      run: |
        cd mtls_server
        mkdir -p target/
        cp build/mtls_server target/ 2>/dev/null || :
        cp build/*.so target/ 2>/dev/null || :
        cp build/*.pem target/ 2>/dev/null || :
        cp build/*.der target/ 2>/dev/null || :
        echo "PACKAGE_PATH=$(pwd)/target" >> $GITHUB_ENV

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: mtls-server-release
        path: ${{ env.PACKAGE_PATH }}
