name: run build

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mtls-server:
    runs-on: ubuntu-latest

    outputs:
      release_ready: ${{ steps.tag_check.outputs.is_release }}

    steps:
    - uses: actions/checkout@v4

    - name: Install VCPKG and dependencies
      id: vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install uthash kcp wolfssl

        # Export and extract toolchain path
        EXPORT_OUTPUT=$(./vcpkg export uthash kcp wolfssl --raw --output=temp)
        echo "======EXPORT_OUTPUT=$EXPORT_OUTPUT======"
        TOOLCHAIN_PATH=$(echo "$EXPORT_OUTPUT" | grep -oP 'CMAKE_TOOLCHAIN_FILE=\K[^ ]*')
        echo "VCPKG_CMAKE_TOOLCHAIN=$TOOLCHAIN_PATH" >> $GITHUB_ENV
        
        # Debug output
        echo "Extracted toolchain path: $TOOLCHAIN_PATH"

    - name: Configure with CMake
      run: |
        echo "current pwd: $(pwd)"
        ls -lh
        cd mtls_server
        cmake -S ./ -B ./build -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_CMAKE_TOOLCHAIN }}

    - name: Build
      run: |
        cd mtls_server
        cmake --build ./build --config Release
        ls -lh ./build

    - name: Package and export
      run: |
        cd mtls_server
        mkdir -p release/
        cp build/mtls_server release/ 2>/dev/null || :
        cp -r assets/ release/ 2>/dev/null || :
        tar czvf mtls-server-release.tar.gz -C release .
        echo "PACKAGE_PATH=$(pwd)/mtls-server-release.tar.gz" >> $GITHUB_ENV

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: mtls-server-release
        path: ${{ env.PACKAGE_PATH }}

  build-dashboard:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: |
          cd api_server/dashboard/
          flutter doctor
          flutter pub get
          
      - name: Build web release
        shell: pwsh
        run: |
          cd api_server/dashboard/
          flutter build web --base-href=/dashboard/

      - name: Package and export
        shell: bash
        run: |
          cd api_server/dashboard/ || exit 1
          mkdir -p release/ || { echo "Failed to create release/"; exit 1; }
          cp -a build/web/. release/ || { echo "Failed to copy files"; exit 1; }
          tar czvf dashboard-release.tar.gz -C release .
          echo "PACKAGE_PATH=$(cygpath -w "$(pwd)/dashboard-release.tar.gz")" >> $GITHUB_ENV

      - name: Upload release package
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-release
          path: ${{ env.PACKAGE_PATH }}

  build-api-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cd api_server
        cargo build --release --verbose
        ls -lh ./target/release/
    - name: Run tests

      run: |
        cd api_server
        cargo test --release --verbose

    - name: Package and export
      run: |
        cd api_server
        mkdir -p release/
        cp target/release/api_server release/ 2>/dev/null || :
        tar czvf api-server-release.tar.gz -C release .
        echo "PACKAGE_PATH=$(pwd)/api-server-release.tar.gz" >> $GITHUB_ENV

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: api-server-release
        path: ${{ env.PACKAGE_PATH }}

  build-windows-client:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install VCPKG and dependencies
        id: vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install uthash cjson wolfssl

          $EXPORT_OUTPUT = .\vcpkg export uthash cjson wolfssl --raw --output=temp
          Write-Output "======EXPORT_OUTPUT=$EXPORT_OUTPUT======"
          $TOOLCHAIN_PATH = $EXPORT_OUTPUT | Select-String -Pattern "CMAKE_TOOLCHAIN_FILE=([^\s]+)" | ForEach-Object { $_.Matches.Groups[1].Value }
          Write-Output "Extracted toolchain path: $TOOLCHAIN_PATH"
          echo "VCPKG_CMAKE_TOOLCHAIN=$TOOLCHAIN_PATH" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
  
      - name: Configure with CMake
        run: |
          echo "current pwd: $(pwd)"
          cd EasyNetwork\libEasyNetwork
          cmake -S ./ -B ./build -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_CMAKE_TOOLCHAIN }}
          
      - name: Build
        run: |
          cd EasyNetwork\libEasyNetwork
          cmake --build ./build --config Release

      - name: Install dependencies
        run: |
          cd EasyNetwork\flutter\
          flutter doctor
          flutter pub get
          flutter pub run ffigen --config ffigen.yaml
          
      - name: Build Windows release
        shell: bash
        run: |
          cd EasyNetwork/flutter/
          flutter build windows --release
          ls build/windows/x64/runner/Release/

      - name: Package and export
        shell: bash
        run: |
          cd EasyNetwork/flutter/ || exit 1
          mkdir -p release/ || { echo "Failed to create release/"; exit 1; }
          cp -a build/windows/x64/runner/Release/. release/ || { echo "Failed to copy files"; exit 1; }
          tar czvf windows-client-release.tar.gz -C release .
          echo "PACKAGE_PATH=$(cygpath -w "$(pwd)/windows-client-release.tar.gz")" >> $GITHUB_ENV

      - name: Upload release package
        uses: actions/upload-artifact@v4
        with:
          name: windows-client-release
          path: ${{ env.PACKAGE_PATH }}

  build-api-server-aarch64v8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.82"
          override: true
          default: true
          components: rustfmt
          profile: minimal
          target: aarch64-unknown-linux-gnu

      - name: Build
        uses: ClementTsang/cargo-action@v0.0.3
        with:
          command: build
          args: --release --all-features --target=aarch64-unknown-linux-gnu
          directory: api_server
          use-cross: true

      - name: Package and export
        run: |
          cd api_server
          mkdir -p release
          cp target/aarch64-unknown-linux-gnu/release/api_server release/ 2>/dev/null || :
          tar czvf api-server-release-aarch64v8.tar.gz -C release .
          echo "PACKAGE_PATH=$(pwd)/api-server-release-aarch64v8.tar.gz" >> $GITHUB_ENV

      - name: Upload release package
        uses: actions/upload-artifact@v4
        with:
          name: api-server-release-aarch64v8
          path: ${{ env.PACKAGE_PATH }}
          if-no-files-found: error

  build-mtls-server-aarch64v8:
    runs-on: ubuntu-latest

    outputs:
      release_ready: ${{ steps.tag_check.outputs.is_release }}

    steps:
    - uses: actions/checkout@v4

    - name: Install ARM cross-compilation toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Install VCPKG and dependencies
      id: vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install uthash kcp wolfssl --triplet arm64-linux
        VCPKG_PATH=$(pwd)
        TOOLCHAIN_PATH=$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake
        echo "VCPKG_CMAKE_TOOLCHAIN=$TOOLCHAIN_PATH" >> $GITHUB_ENV
        echo "VCPKG_PATH=$VCPKG_PATH" >> $GITHUB_ENV
        find $VCPKG_PATH/installed/arm64-linux -name "*wolfssl*.cmake"

    - name: Configure with CMake
      run: |
        echo "current pwd: $(pwd)"
        cd mtls_server
        cmake -S ./ -B ./build \
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_CMAKE_TOOLCHAIN }} \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=arm64 \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -Dwolfssl_DIR=${{ env.VCPKG_PATH }}/installed/arm64-linux/share/wolfssl

    - name: Build
      run: |
        cd mtls_server
        cmake --build ./build --config Release

    - name: Package and export
      run: |
        cd mtls_server
        mkdir -p release/
        cp build/mtls_server release/ 2>/dev/null || :
        cp -r assets/ release/ 2>/dev/null || :
        tar czvf mtls-server-release-aarch64v8.tar.gz -C release .
        echo "PACKAGE_PATH=$(pwd)/mtls-server-release-aarch64v8.tar.gz" >> $GITHUB_ENV

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: mtls-server-release-aarch64v8
        path: ${{ env.PACKAGE_PATH }}
  
  release:
    needs: [build-mtls-server, build-dashboard, build-api-server, build-windows-client, build-api-server-aarch64v8, build-mtls-server-aarch64v8]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download mtls server artifact
        uses: actions/download-artifact@v4
        with:
          name: mtls-server-release
          path: release-artifacts/mtls-server

      - name: Download dashboard artifact
        uses: actions/download-artifact@v4
        with:
          name: dashboard-release
          path: release-artifacts/dashboard

      - name: Download api server artifact
        uses: actions/download-artifact@v4
        with:
          name: api-server-release
          path: release-artifacts/api-server

      - name: Download windows client artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-client-release
          path: release-artifacts/windows-client

      - name: Download api server aarch64v8 artifact
        uses: actions/download-artifact@v4
        with:
          name: api-server-release-aarch64v8
          path: release-artifacts/api-server-aarch64v8

      - name: Download mtls server aarch64v8 artifact
        uses: actions/download-artifact@v4
        with:
          name: mtls-server-release-aarch64v8
          path: release-artifacts/mtls-server-aarch64v8
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            EasyNetwork 版本发布
            - 包含: mtls server, dashboard, api server, windows client, api server aarch64v8, mtls server aarch64v8
          files: |
            release-artifacts/mtls-server/*
            release-artifacts/dashboard/*
            release-artifacts/api-server/*
            release-artifacts/windows-client/*
            release-artifacts/api-server-aarch64v8/*
            release-artifacts/mtls-server-aarch64v8/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get current date
        id: get-current-date
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
